[package]
name = "xtask"
description = "Build, test, and release automation tasks for the Tracel SDK workspace."
version.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
tracel-xtask = { workspace = true, features = ["build", "bump", "check", "compile", "doc", "fix", "publish", "test", "validate", "utils-time"] }
strum = { workspace = true }
