[alias]
xtask = "run --target-dir target/xtask/debug --package xtask --bin xtask --"

#burn = { version = "0.19.0", branch = "refactor/metric-loggers", git = "https://github.com/tracel-ai/burn" }
burn = { version = "0.19.0", path = "../burn/crates/burn"}