[package]
name = "tracel-artifact"
description = "Artifact bundle and transfer utilities for Tracel SDK."
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["fs"]
# Bundles on the local filesystem.
fs = ["dep:tempfile"]

[dependencies]
bytes = { workspace = true }
futures = { workspace = true, features = ["std", "executor"] }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }
tracel-task = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-timer = { workspace = true }
reqwest = { workspace = true, features = ["stream", "default-tls"] }
tracel-task = { workspace = true, features = ["tokio"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-timer = { workspace = true, features = ["wasm-bindgen"] }
reqwest = { workspace = true, features = ["stream"] }

[dev-dependencies]
serde_json = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt"] }
