[package]
name = "tracel-station"
description = "Burn-free client for a Tracel Station."
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tracel-artifact = { workspace = true }
tracel-client = { workspace = true }
tracel-datasets = { workspace = true }
tracel-experiment = { workspace = true }
tracel-experiment-remote = { workspace = true }
tracel-models = { workspace = true }
url = { workspace = true }
