name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  # --------------------------------------------------------------------------------
  tracel-artifact:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-artifact
      tag-validation: false
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-datasets:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-datasets
      tag-validation: false
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-inference:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-inference
      tag-validation: false
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-experiment:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-experiment
      tag-validation: false
    needs:
      - tracel-artifact
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-models:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-models
      tag-validation: false
    needs:
      - tracel-artifact
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-experiment-remote:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-experiment-remote
      tag-validation: false
    needs:
      - tracel-artifact
      - tracel-experiment
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-runner:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-runner
      tag-validation: false
    needs:
      - tracel-experiment
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-app:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-app
      tag-validation: false
    needs:
      - tracel-experiment
      - tracel-inference
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-console:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-console
      tag-validation: false
    needs:
      - tracel-artifact
      - tracel-datasets
      - tracel-experiment
      - tracel-experiment-remote
      - tracel-inference
      - tracel-models
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-station:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-station
      tag-validation: false
    needs:
      - tracel-artifact
      - tracel-datasets
      - tracel-experiment
      - tracel-experiment-remote
      - tracel-models
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-core:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-core
      tag-validation: false
    needs:
      - tracel-artifact
      - tracel-console
      - tracel-datasets
      - tracel-experiment
      - tracel-experiment-remote
      - tracel-inference
      - tracel-models
      - tracel-station
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel
      tag-validation: false
    needs:
      - tracel-app
      - tracel-artifact
      - tracel-console
      - tracel-core
      - tracel-datasets
      - tracel-experiment
      - tracel-inference
      - tracel-models
      - tracel-runner
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
