name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  # --------------------------------------------------------------------------------
  tracel-macros:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel-macros
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-inference:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel-inference
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-artifact:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel-artifact
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-experiment:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel-experiment
    needs:
      - tracel-artifact
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-fleet:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel-fleet
    needs:
      - tracel-artifact
      - tracel-inference
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-core:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel-core
    needs:
      - tracel-artifact
      - tracel-experiment
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel-app:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel-app
    needs:
      - tracel-artifact
      - tracel-core
      - tracel-experiment
      - tracel-fleet
      - tracel-inference
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
  # --------------------------------------------------------------------------------
  tracel:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: tracel
    needs:
      - tracel-artifact
      - tracel-core
      - tracel-experiment
      - tracel-fleet
      - tracel-inference
      - tracel-macros
      - tracel-app
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
